package uk.gov.justice.digital.hmpps.hmppsmanageadjudicationsapi.services

enum class Descriptions(val description: String) {
  YOI_1_ADULT_1("Commits any assault"),
  YOI_3_ADULT_2("Detains any person against their will"),
  YOI_4("Denies access to any part of the young offender institution to any officer or any person (other than an inmate) who is at the young offender institution for the purpose of working there"),
  YOI_5_ADULT_4("Fights with any person"),
  YOI_6_ADULT_5("Intentionally endangers the health or personal safety of others or, by their conduct, is reckless whether such health or personal safety is endangered"),
  YOI_7("Intentionally obstructs an officer in the execution of his duty, or any person (other than an inmate) who is at the young offender institution for the purpose of working there, in the performance of his work"),
  YOI_8("Escapes or absconds from a young offender institution or from legal custody"),
  YOI_9("Failing to comply with conditions of release under rule 5 which relates to temporary release"),
  YOI_10("Is found with any substance in his urine which demonstrates that a controlled drug (or specified drug) has, whether in prison or while on temporary release under rule 5 (or rule 5A), been administered to him by himself or by another person (but subject to rule 56)"),
  YOI_11_ADULT_10("Is intoxicated as a consequence of knowingly consuming any alcoholic beverage"),
  YOI_12("Knowingly consumes any alcoholic beverage other than that provided to them pursuant to a written order under rule 21 (alcohol and tobacco) (1)"),
  YOI_13_ADULT_12("Has in his possession either (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have"),
  YOI_14_ADULT_13("Sells or delivers to any person any unauthorised article"),
  YOI_15_ADULT_14("Sells or, without permission, delivers to any person any article which they are allowed to have only for their own use"),
  YOI_16("Takes improperly any article belonging to another person or to a young offender institution"),
  YOI_17("Intentionally or recklessly sets fire to any part of a young offender institution or any other property, whether or not his own"),
  YOI_19_ADULT_24A("Displays, attaches or draws on any part of a prison, or on any other property, threatening, abusive or insulting racist words, drawings, symbols or other material"),
  YOI_20_ADULT_18("Absents himself from any place he is required to be or is present at any place where they are not authorised to be"),
  YOI_21_ADULT_19("Is disrespectful to any officer, or any person (other than a prisoner) who is at the prison for the purpose of working there, or any person visiting a prison"),
  YOI_22_YOI_23_ADULT_20("Uses threatening, abusive or insulting words or behaviour"),
  YOI_24_ADULT_21("Intentionally fails to work properly or, being required to work, refuses to do so"),
  YOI_25_ADULT_22("Disobeys any lawful order"),
  YOI_26_ADULT_23("Disobeys or fails to comply with any rule or regulation applying to them"),
  YOI_27("Receives any controlled drug, or, without the consent of an officer, any other article, during the course of a visit (not being an interview such as is mentioned in rule 16)"),
  ADULT_3("Denies access to any part of the prison to any officer or any person (other than a prisoner) who is at the prison for the purpose of working there"),
  ADULT_6("Intentionally obstructs an officer in the execution of his duty, or any person (other than a prisoner) who is at the prison for the purpose of working there, in the performance of their work\n"),
  ADULT_7("Escapes or absconds from legal custody"),
  ADULT_8("Failing to comply with conditions of release under rule 9 which relates to temporary release"),
  ADULT_9("Is found with any substance in his urine which demonstrates that a controlled drug (or specified drug) has, whether in prison or while on temporary release under rule 9 (or rule 9A), been administered to him by himself or by another person (but subject to rule 52)"),
  ADULT_11("Knowingly consumes any alcoholic beverage other than that provided to them pursuant to a written order under rule 25 (alcohol and tobacco) (1)"),
  ADULT_15("Takes improperly any article belonging to another person or to a prison"),
  ADULT_16("Intentionally or recklessly sets fire to any part of a prison or any other property, whether or not their own"),
  ADULT_17("Destroys or damages any part of a prison or any other property, other than their own"),
  ADULT_24("Receives any controlled drug, or, without the consent of an officer, any other article, during the course of a visit (not being an interview such as is mentioned in rule 38, which relates to visits from legal advisors)"),
  DEFAULT("")
}

class OffenceCodeParagraphs {

  private val lookup = mapOf(
    "55:2" to "YOI_1_ADULT_1",
    "55:1A" to "YOI_1_ADULT_1",
    "55:1L" to "YOI_1_ADULT_1",
    "55:1M" to "YOI_1_ADULT_1",
    "55:1E" to "YOI_1_ADULT_1",
    "55:5" to "YOI_5_ADULT_4",
    "55:6" to "YOI_6_ADULT_5",
    "55:8" to "YOI_8",
    "55:9D" to "YOI_9",
    "55:9E" to "YOI_9",
    "55:13" to "YOI_13_ADULT_12",
    "55:13A" to "YOI_13_ADULT_12",
    "55:15" to "YOI_15_ADULT_14",
    "55:14B" to "YOI_14_ADULT_13",
    "55:16" to "YOI_16",
    "55:27" to "YOI_27",
    "55:26B" to "YOI_26_ADULT_23",
    "55:26C" to "YOI_26_ADULT_23",
    "55:10" to "YOI_10",
    "55:13C" to "YOI_13_ADULT_12",
    "55:13B" to "YOI_13_ADULT_12",
    "55:11" to "YOI_11_ADULT_10",
    "55:12" to "YOI_12",
    "55:17" to "YOI_17",
    "55:19" to "YOI_19_ADULT_24A",
    "55:21B" to "YOI_21_ADULT_19",
    "55:21C" to "YOI_21_ADULT_19",
    "55:21A" to "YOI_21_ADULT_19",
    "55:23" to "YOI_22_YOI_23_ADULT_20",
    "55:20" to "YOI_22_YOI_23_ADULT_20",
    "55:25" to "YOI_25_ADULT_22",
    "55:26" to "YOI_26_ADULT_23",
    "55:3A" to "YOI_3_ADULT_2",
    "55:3C" to "YOI_3_ADULT_2",
    "55:3D" to "YOI_3_ADULT_2",
    "55:3B" to "YOI_3_ADULT_2",
    "55:4" to "YOI_4",
    "55:7" to "YOI_7",
    "55:20A" to "YOI_20_ADULT_18",
    "55:20B" to "YOI_20_ADULT_18",
    "55:24" to "YOI_24_ADULT_21",
    "51:1A" to "YOI_1_ADULT_1",
    "51:1B" to "YOI_1_ADULT_1",
    "51:1J" to "YOI_1_ADULT_1",
    "51:1N" to "YOI_1_ADULT_1",
    "51:1F" to "YOI_1_ADULT_1",
    "51:4" to "YOI_5_ADULT_4",
    "51:5" to "YOI_6_ADULT_5",
    "51:7" to "ADULT_7",
    "51:8D" to "ADULT_8",
    "51:8E" to "ADULT_8",
    "51:12" to "YOI_13_ADULT_12",
    "51:12A" to "YOI_13_ADULT_12",
    "51:14" to "YOI_15_ADULT_14",
    "51:13B" to "YOI_14_ADULT_13",
    "51:15" to "ADULT_15",
    "51:24" to "ADULT_24",
    "51:23AP" to "YOI_26_ADULT_23",
    "51:25Z" to "YOI_26_ADULT_23",
    "51:9" to "ADULT_9",
    "51:12AQ" to "YOI_13_ADULT_12",
    "51:10" to "YOI_11_ADULT_10",
    "51:11" to "ADULT_11",
    "51:16" to "ADULT_16",
    "51:24A" to "YOI_19_ADULT_24A",
    "51:17" to "ADULT_17",
    "51:19B" to "YOI_21_ADULT_19",
    "51:19C" to "YOI_21_ADULT_19",
    "51:19A" to "YOI_21_ADULT_19",
    "51:20A" to "YOI_22_YOI_23_ADULT_20",
    "51:20" to "YOI_22_YOI_23_ADULT_20",
    "51:22" to "YOI_25_ADULT_22",
    "51:23" to "YOI_26_ADULT_23",
    "51:2A" to "YOI_3_ADULT_2",
    "51:2C" to "YOI_3_ADULT_2",
    "51:2D" to "YOI_25_ADULT_22",
    "51:2B" to "YOI_3_ADULT_2",
    "51:3" to "ADULT_3",
    "51:6" to "ADULT_6",
    "51:18A" to "YOI_20_ADULT_18",
    "51:18B" to "YOI_20_ADULT_18",
    "51:21" to "YOI_24_ADULT_21"
  )

  fun getParagraphDescription(nomisPrefixOffenceCode: String): String {
    val description = lookup[nomisPrefixOffenceCode] ?: Descriptions.DEFAULT.name
    return Descriptions.valueOf(description).description
  }
}
