version: "3"
services:
  hmpps-manage-adjudications-api:
    build: .
    container_name: hmpps-manage-adjudications-api
    networks:
      - hmpps
    ports:
      - "8080:8080"
    depends_on:
      - hmpps-auth
      - hmpps-manage-adjudications-api-db
      - prison-api
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - PRISON_API_ENDPOINT_URL=http://prison-api:8080
      - OAUTH_ENDPOINT_URL=http://hmpps-auth:8080/auth
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://hmpps-auth:8080/auth/.well-known/jwks.json
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hmpps-manage-adjudications-api-db:5432/adjudications
      - SPRING_DATASOURCE_USERNAME=adjudications
      - SPRING_DATASOURCE_PASSWORD=adjudications

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev,nomis
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - NOMIS_ENDPOINT_URL=http://nomis-user-roles-api:8080

  nomis-user-roles-api:
    image: quay.io/hmpps/nomis-user-roles-api:latest
    networks:
      - hmpps
    container_name: nomis-user-roles-api
    depends_on:
      - hmpps-auth
    ports:
      - "8084:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - API_BASE_URL_OAUTH=http://hmpps-auth:8080/auth

  prison-api:
    image: quay.io/hmpps/prison-api:latest
    networks:
      - hmpps
    container_name: prison-api
    depends_on:
      - hmpps-auth
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  hmpps-manage-adjudications-api-db:
    image: postgres
    container_name: hmpps-manage-adjudications-api-db
    restart: always
    networks:
      - hmpps
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=adjudications
      - POSTGRES_USER=adjudications
      - POSTGRES_DB=adjudications
networks:
  hmpps:
