prison.api.endpoint.url: https://prison-api-dev.prison.service.justice.gov.uk
oauth.endpoint.url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
      client:
        registration:
          prison-nomis-api:
            provider: hmpps-auth
            client-id: ${system.client.id}
            client-secret: ${system.client.secret}
            authorization-grant-type: client_credentials
            scope: read,write
          prisoner-search-api:
            provider: hmpps-auth
            client-id: ${system.client.id}
            client-secret: ${system.client.secret}
            authorization-grant-type: client_credentials
            scope: read
          prison-location-api:
            provider: hmpps-auth
            client-id: ${system.client.id}
            client-secret: ${system.client.secret}
            authorization-grant-type: client_credentials
            scope: read
        provider:
          hmpps-auth:
            token-uri: ${hmpps.auth.url}/oauth/token