spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

  datasource:
    url: jdbc:postgresql://localhost:5432/hmpps-manage-adjudications-api-db
    username: test
    password: test
    continueOnError: true