spring:
  security:
    oauth2:
      resource-server:
        jwt:
          public-key-location: classpath:local-public-key.pub

  datasource:
    url: jdbc:postgresql://localhost:5432/manage-adjudications
    username: adjudications
    password: adjudications