apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmppps-manage-adjudications-api-check-and-lock
spec:
  schedule: "0 3 * * 1-5"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: housekeeping
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 -XPUT http://hmpps-manage-adjudications-api/scheduled-tasks/check-nomis-created-hearing-outcomes-for-locking
          restartPolicy: Never
