apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmppps-manage-adjudications-api-migration-fix
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: housekeeping
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 -XPOST http://hmpps-manage-adjudications-api/scheduled-tasks/migration-fix
          restartPolicy: Never