---
# Per environment values which override defaults in hmpps-manage-adjudications-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-adjudications-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    PRISON_API_ENDPOINT_URL: https://prison-api-dev.prison.service.justice.gov.uk
    FEATURE_ASYNC_ADJUDICATIONS: true
    FEATURE_NOMIS_SOURCE_OF_TRUTH: true
    FEATURE_SKIP_EXISTING: true
    FEATURE_ASYNC_HEARINGS: true

  allowlist: null

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
  rdsAlertsDatabases:
    cloud-platform-1ec554469922ee81: "Manage Adjudications API"
  sqsAlertsQueueNames:
    - "dps-core-dev-prisoner-event-queue"
    - "dps-core-dev-prisoner-event-dlq"

environment: dev
