---
# Per environment values which override defaults in hmpps-manage-adjudications-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-adjudications-api-preprod.hmpps.service.justice.gov.uk

  env:
    JAVA_OPTS: "-Xmx1G"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    PRISON_API_ENDPOINT_URL: https://api-preprod.prison.service.justice.gov.uk
    FEATURE_ASYNC_ADJUDICATIONS: true
    FEATURE_NOMIS_SOURCE_OF_TRUTH: true
    FEATURE_SKIP_EXISTING: false

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
  rdsAlertsDatabases:
    cloud-platform-6c035586d92ac925: "Manage Adjudications API"
  sqsAlertsQueueNames:
    - "dps-core-preprod-prisoner-event-queue"
    - "dps-core-preprod-prisoner-event-dlq"

environment: preprod
