---
# Per environment values which override defaults in hmpps-manage-adjudications-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-adjudications-api-dev.hmpps.service.justice.gov.uk
    modsecurity_enabled: true
    modsecurity_github_team: "hmpps-adjudications"
    modsecurity_snippet: |
      SecRuleEngine On
      # Default is only GET HEAD POST OPTIONS so need to include PUT etc.
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT DELETE"
      # Missing User Agent Header
      SecRuleRemoveById 920320


  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_BASE_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    PRISONS_NOMIS_LOCATION_BASE_DOMAIN: https://nomis-sync-prisoner-mapping-dev.hmpps.service.justice.gov.uk
    PRISONS_LOCATION_BASE_DOMAIN: https://locations-inside-prison-api-dev.hmpps.service.justice.gov.uk
    PRISONER_SEARCH_BASE_DOMAIN: https://prison-api-dev.prison.service.justice.gov.uk
    PRISON_TIMEOUT: "10s"

  allowlist: null

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
  rdsAlertsDatabases:
    cloud-platform-1ec554469922ee81: "Manage Adjudications API"
  sqsAlertsQueueNames:
    - "dps-core-dev-prisoner-event-queue"
    - "dps-core-dev-prisoner-event-dlq"

environment: dev
