---
# Per environment values which override defaults in hmpps-manage-adjudications-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-adjudications-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_BASE_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    PRISONS_NOMIS_LOCATION_BASE_DOMAIN: https://nomis-sync-prisoner-mapping-preprod.hmpps.service.justice.gov.uk
    PRISONS_LOCATION_BASE_DOMAIN: https://locations-inside-prison-api-preprod.hmpps.service.justice.gov.uk
    PRISONER_SEARCH_BASE_DOMAIN: https://prisoner-search-preprod.prison.service.justice.gov.uk
    PRISON_TIMEOUT: "10s"

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
  rdsAlertsDatabases:
    cloud-platform-6c035586d92ac925: "Manage Adjudications API"
  sqsAlertsQueueNames:
    - "dps-core-preprod-prisoner-event-queue"
    - "dps-core-preprod-prisoner-event-dlq"

environment: preprod
